version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - service-a-db
      - service-a-cache

  service-a-db:
    image: postgres:15
    environment:
      POSTGRES_DB: service_a
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  service-a-cache:
    image: redis:7

  service-b:
    build: ./service-b
    ports:
      - "8082:8080"

  service-c:
    build: ./service-c
    ports:
      - "8083:8080"
